### ISSUE TITLE
Windows: Reading MEF from different drive than C.

### ISSUE THREAD

**Issue by nelagri** [msel-source/pymef#15]
Hi Jan,

although saving of MEF files to different drives than C works just fine, I encounter the Access Violation Error (0xc0000005) when I try to read such file. When I move the file to C Drive, the file can be loaded without any problem. Could you, please, take a look at this issue? 

Thank you.

**Comment by MaxvandenBoom** [comment]
@nelagri Know your issue was some time ago, but if you don't want to wait, you can fix it yourself.
The bug is in the meflib base that pymef uses, see: https://github.com/msel-source/meflib/issues/9

**Comment by cimbi** [comment]
Hi gyus, sorry I was out of the loop. Apperently the notifications were off and I was not aware about the issues. Closing this issue since it is an upstream problem of meflib. Will solve it there.
