### ISSUE TITLE
Large numbers storing

### ISSUE THREAD

**Issue by nelagri** [msel-source/pymef#16]
I'm struggling with saving of large floats to a MEF file. Since only 32-bit intergers can be stored in MEF files and I have to "rescue" at least 3 digits after the decimal point (because my sampling frequency is 1 kHz), I multiply values of a signal by 1e3 and set the units conversion to 0.001. Thereby I limit the maximal value which can be stored to (2^31-1)/1000, but I need to save much larger values.

Could you, please, tell me what is the best practice to handle this issue? I have found that, maybe, I need to adopt fixed compression ratio or mean residual ratio, but I didn't find any detailed description of how to use these ratios. 

Thank you in advance.

**Comment by cimbi** [comment]
This depends on the dynamic range of the device. I wonder why there are such big numbers and if they even make sense. Floats are not exactly discrete. We were dealing with a similar problem at one point but then realized that the last digits after the decimal point do not make sens physically (i.e. the recording machine is not capable to record such minute changes in amplitude). What is the basic unit of the data you need to convert?

**Comment by cimbi** [comment]
Closing as stale...
