### ISSUE TITLE
Access violation (memory allocation check) when reading data in time units

### ISSUE THREAD

**Issue by MaxvandenBoom** [msel-source/pymef#18]
Hi Dan and Jan,

While translating your wrapper to Matlab, I encountered an error which also occurs in PyMef. When you read the data (using 'read_mef_ts_data' function in 'pymef3_file.c') and use time units to specify what to read, then our wrappers allow for the passing of a start_time before the start uutc of the data or the data or an end_time after the end uutc of the data; padding with NaN before and after if needed.

However, when a very small value is passed as start_time or/and a big value is passed as end_time, then the buffer can get quite big (to try this yourself, just request data with a start_time of 0).

When allocating the buffer (line 1858):
`decomp_data = (si4 *) malloc((size_t) (num_samps * sizeof(si4)));`
it can fail, but there is no check on the allocation; if it does fail to allocate then it causes an access violation very shortly after.

To solve this, I implemented a check on the failure to allocate the buffer  (decomp_data == NULL) after the line above, to account for this scenario. Something you might want to implement as well.

**Comment by cimbi** [comment]
Great,  thanks. I'll look into this and try to fix it in pymef
