### ISSUE TITLE
pymef v0.3.5  numpy requirement in pip

### ISSUE THREAD

**Issue by SweetVlad** [msel-source/pymef#4]
## Problem Description
- pymef version 0.3.5 requires new version of numpy v 1.x.0 (with 1.16.0 works fine)

- pymef v 0.3.5 doesn't work with numpy 1.14.3

**Comment by cimbi** [comment]
I am trying to stay up to date with the latest and greatest. I am not sure if it is desirable to ensure backward compatibility. Leaving this open for now...
